-- SIGVE · Inventario de la sede
-- Ejecutar una sola vez en Supabase > SQL Editor.
create table if not exists public.inventario_sede (
  id bigint generated by default as identity primary key,
  articulo text not null,
  categoria text not null default 'Otros',
  cantidad integer not null default 1 check (cantidad >= 0),
  estado text not null default 'Bueno' check (estado in ('Bueno','Regular','Malo')),
  ubicacion text,
  observaciones text,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  creado_por uuid default auth.uid()
);
alter table public.inventario_sede enable row level security;
drop policy if exists "Admin gestiona inventario sede" on public.inventario_sede;
create policy "Admin gestiona inventario sede" on public.inventario_sede
for all to authenticated using (public.es_admin()) with check (public.es_admin());
create index if not exists inventario_sede_activo_idx on public.inventario_sede(activo);
create index if not exists inventario_sede_categoria_idx on public.inventario_sede(categoria);
