-- Portal Villa El Trigal v7.0 / Portal 2.0
-- Ejecutar una sola vez en Supabase > SQL Editor.

create extension if not exists pgcrypto;

create or replace function public.es_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.administradores a where a.user_id=auth.uid() and a.activo=true)
$$;

create table if not exists public.configuracion_gestion (
 id int primary key default 1 check(id=1), valor_arriendo numeric(12,0) not null default 40000,
 abono_minimo numeric(12,0) not null default 10000, valor_certificado numeric(12,0) not null default 1000,
 valor_cuota numeric(12,0) not null default 2000, valor_zumba numeric(12,0) not null default 2000,
 edad_max_navidad int not null default 10, actualizado_en timestamptz default now(), actualizado_por uuid references auth.users(id)
);
insert into public.configuracion_gestion(id) values(1) on conflict(id) do nothing;

create table if not exists public.socios (
 id uuid primary key default gen_random_uuid(), numero_socio bigint generated by default as identity unique,
 nombre_completo text not null, rut text not null unique, direccion text not null, telefono text, correo text,
 fecha_ingreso date not null default current_date, estado text not null default 'activo' check(estado in ('activo','inactivo','pendiente','rechazado')),
 observaciones text, foto_url text, creado_en timestamptz default now(), actualizado_en timestamptz default now(), creado_por uuid references auth.users(id)
);
create table if not exists public.grupo_familiar (
 id uuid primary key default gen_random_uuid(), socio_id uuid not null references public.socios(id) on delete cascade,
 nombre_completo text not null, rut text, fecha_nacimiento date not null, sexo text not null check(sexo in ('F','M')),
 parentesco text not null default 'Hijo(a)', direccion text not null, observaciones text,
 creado_en timestamptz default now(), actualizado_en timestamptz default now(), creado_por uuid references auth.users(id)
);
create unique index if not exists grupo_familiar_rut_unique on public.grupo_familiar(rut) where rut is not null and rut<>'';

create table if not exists public.solicitudes_socios (
 id uuid primary key default gen_random_uuid(), nombre_completo text not null, rut text not null, direccion text not null,
 telefono text not null, correo text, observaciones text, estado text not null default 'pendiente' check(estado in ('pendiente','aprobado','rechazado')),
 creado_en timestamptz default now(), revisado_en timestamptz, revisado_por uuid references auth.users(id)
);

create table if not exists public.reservas_sede (
 id uuid primary key default gen_random_uuid(), nombre_arrendatario text not null, rut text, telefono text not null,
 fecha_evento date not null, hora_inicio time not null default '08:00', hora_termino time not null default '22:00',
 tipo text not null default 'arriendo' check(tipo in ('arriendo','actividad','bloqueo','zumba')),
 descripcion text, valor_total numeric(12,0) not null default 40000,
 estado text not null default 'pendiente' check(estado in ('pendiente','aprobado','confirmado','finalizado','cancelado','archivado')),
 whatsapp_enviado boolean not null default false, creado_en timestamptz default now(), actualizado_en timestamptz default now(), creado_por uuid references auth.users(id)
);
create unique index if not exists reserva_fecha_unica_activa on public.reservas_sede(fecha_evento) where estado not in ('cancelado','archivado');

create table if not exists public.movimientos_financieros (
 id uuid primary key default gen_random_uuid(), fecha date not null default current_date,
 tipo text not null check(tipo in ('ingreso','gasto','transferencia')),
 concepto text not null, categoria text, monto numeric(12,0) not null check(monto>0),
 fondo text check(fondo in ('caja','banco')), fondo_origen text check(fondo_origen in ('caja','banco')),
 fondo_destino text check(fondo_destino in ('caja','banco')), reserva_id uuid references public.reservas_sede(id) on delete set null,
 socio_id uuid references public.socios(id) on delete set null, comprobante_url text, proveedor text, numero_documento text,
 observaciones text, sin_respaldo boolean not null default false, creado_en timestamptz default now(), creado_por uuid references auth.users(id),
 constraint movimiento_fondos_validos check(
   (tipo in ('ingreso','gasto') and fondo is not null and fondo_origen is null and fondo_destino is null) or
   (tipo='transferencia' and fondo is null and fondo_origen is not null and fondo_destino is not null and fondo_origen<>fondo_destino)
 )
);

create table if not exists public.certificados_emitidos (
 id uuid primary key default gen_random_uuid(), numero bigint generated by default as identity unique,
 socio_id uuid references public.socios(id) on delete set null, nombre text not null, rut text not null, direccion text not null,
 tipo text not null default 'Residencia', fecha date not null default current_date, valor numeric(12,0) not null default 1000,
 movimiento_id uuid references public.movimientos_financieros(id) on delete set null, observaciones text, creado_por uuid references auth.users(id), creado_en timestamptz default now()
);

alter table public.configuracion_gestion enable row level security;
alter table public.socios enable row level security;
alter table public.grupo_familiar enable row level security;
alter table public.solicitudes_socios enable row level security;
alter table public.reservas_sede enable row level security;
alter table public.movimientos_financieros enable row level security;
alter table public.certificados_emitidos enable row level security;

do $$ declare t text; begin
 foreach t in array array['configuracion_gestion','socios','grupo_familiar','reservas_sede','movimientos_financieros','certificados_emitidos'] loop
  execute format('drop policy if exists "Admin gestiona %s" on public.%I',t,t);
  execute format('create policy "Admin gestiona %s" on public.%I for all to authenticated using (public.es_admin()) with check (public.es_admin())',t,t);
 end loop;
end $$;

drop policy if exists "Publico crea solicitud socio" on public.solicitudes_socios;
create policy "Publico crea solicitud socio" on public.solicitudes_socios for insert to anon,authenticated with check(estado='pendiente');
drop policy if exists "Admin revisa solicitudes socio" on public.solicitudes_socios;
create policy "Admin revisa solicitudes socio" on public.solicitudes_socios for all to authenticated using(public.es_admin()) with check(public.es_admin());

-- Bucket privado para respaldos financieros (se crea si no existe)
insert into storage.buckets(id,name,public) values('respaldos-finanzas','respaldos-finanzas',false) on conflict(id) do nothing;
drop policy if exists "Admin gestiona respaldos finanzas" on storage.objects;
create policy "Admin gestiona respaldos finanzas" on storage.objects for all to authenticated using(bucket_id='respaldos-finanzas' and public.es_admin()) with check(bucket_id='respaldos-finanzas' and public.es_admin());
