(() => {
const cfg=window.PORTAL_CONFIG||{}; const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const state={user:null,admin:null,editing:{}};
const defs={
 anuncios:{title:'Anuncios',fields:[['titulo','Título','text',1],['categoria','Categoría','select',0,['reunion','urgente','actividad','informacion','seguridad','servicio']],['descripcion','Descripción','textarea',1],['fecha_evento','Fecha del evento','date'],['hora_evento','Hora','time'],['lugar','Lugar','text'],['fecha_vencimiento','Vence el','datetime-local'],['destacado','Destacado','checkbox'],['publicado','Publicado','checkbox']]},
 noticias:{title:'Noticias',fields:[['titulo','Título','text',1],['resumen','Resumen','textarea'],['contenido','Contenido','textarea',1],['categoria','Categoría','text'],['imagen_url','Imagen','image'],['destacado','Destacada','checkbox'],['publicado','Publicada','checkbox']]},
 actividades:{title:'Actividades',fields:[['titulo','Título','text',1],['descripcion','Descripción','textarea',1],['fecha','Fecha','date',1],['hora_inicio','Hora inicio','time'],['hora_termino','Hora término','time'],['lugar','Lugar','text'],['imagen_url','Imagen','image'],['publicado','Publicada','checkbox']]},
 galeria:{title:'Galería',fields:[['titulo','Título','text'],['descripcion','Descripción','textarea'],['actividad','Actividad','text'],['fecha','Fecha','date'],['imagen_url','Fotografía','image',1],['publicado','Publicada','checkbox']]}
};
function message(t,bad=false){$('global-message').textContent=t;$('global-message').className='form-message '+(bad?'error':'success');setTimeout(()=>{$('global-message').textContent=''},4500)}
function fieldHtml(f){const[n,l,t,r,opts]=f;if(t==='textarea')return `<label>${l}<textarea name="${n}" ${r?'required':''}></textarea></label>`;if(t==='select')return `<label>${l}<select name="${n}">${opts.map(o=>`<option value="${o}">${o}</option>`).join('')}</select></label>`;if(t==='checkbox')return `<label class="check"><input name="${n}" type="checkbox" checked> ${l}</label>`;if(t==='image')return `<label>${l}<input name="${n}" type="file" accept="image/*" ${r?'required':''}><small class="current-image"></small></label>`;return `<label>${l}<input name="${n}" type="${t}" ${r?'required':''}></label>`}
function buildForms(){for(const[k,d]of Object.entries(defs)){ $(`form-${k}`).innerHTML=`<section class="panel"><h3>Nuevo/a ${d.title.toLowerCase()}</h3><form data-table="${k}"><input type="hidden" name="id"><div class="form-grid">${d.fields.map(fieldHtml).join('')}</div><div class="actions"><button class="button primary" type="submit">Guardar</button><button class="button secondary cancel" type="button" hidden>Cancelar edición</button></div></form></section>`;}}
async function verify(){const{data:{session}}=await sb.auth.getSession();if(!session)return showLogin();state.user=session.user;const{data,error}=await sb.from('administradores').select('*').eq('user_id',state.user.id).eq('activo',true).single();if(error||!data){await sb.auth.signOut();$('login-message').textContent='Este usuario no tiene permisos de administrador.';return showLogin()}state.admin=data;showAdmin();await loadAll()}
function showLogin(){$('login-view').hidden=false;$('admin-view').hidden=true} function showAdmin(){$('login-view').hidden=true;$('admin-view').hidden=false;$('admin-name').textContent=state.admin?.nombre||state.user.email}
async function upload(file,table){if(!file)return null;const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${table}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const{error}=await sb.storage.from('portal-imagenes').upload(path,file,{cacheControl:'3600',upsert:false});if(error)throw error;return sb.storage.from('portal-imagenes').getPublicUrl(path).data.publicUrl}
async function loadTable(table){const order=table==='actividades'?'fecha':'creado_en';const{data,error}=await sb.from(table).select('*').order(order,{ascending:false});if(error){message(error.message,true);return}renderList(table,data||[]);$(`stat-${table}`)&&( $(`stat-${table}`).textContent=(data||[]).length )}
function renderList(table,rows){const el=$(`list-${table}`);if(!rows.length){el.innerHTML='<div class="panel empty">Todavía no hay publicaciones.</div>';return}el.innerHTML=rows.map(x=>`<article class="item"><div>${x.imagen_url?`<img class="thumb" src="${esc(x.imagen_url)}" alt="">`:''}<h3>${esc(x.titulo||'Sin título')}</h3><p>${esc(x.descripcion||x.resumen||x.contenido||'')}</p><div class="item-meta">${x.publicado===false?'Borrador':'Publicado'}</div></div><div class="actions"><button class="button secondary" data-edit="${x.id}">Editar</button><button class="button danger" data-delete="${x.id}">Eliminar</button></div></article>`).join('');el.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editRow(table,rows.find(r=>r.id===b.dataset.edit)));el.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteRow(table,b.dataset.delete))}
function editRow(table,row){const form=document.querySelector(`form[data-table="${table}"]`);form.id.value=row.id;for(const f of defs[table].fields){const[n,,t]=f;const input=form.elements[n];if(!input)continue;if(t==='checkbox')input.checked=!!row[n];else if(t==='image'){input.required=false;input.closest('label').querySelector('.current-image').textContent=row[n]?'Imagen actual cargada':''}else if(t==='datetime-local'&&row[n])input.value=row[n].slice(0,16);else input.value=row[n]??''}form.closest('.panel').querySelector('h3').textContent='Editar publicación';form.querySelector('.cancel').hidden=false;form.scrollIntoView({behavior:'smooth'})}
function resetForm(form){form.reset();form.id.value='';form.closest('.panel').querySelector('h3').textContent='Nueva publicación';form.querySelector('.cancel').hidden=true;form.querySelectorAll('input[type=file]').forEach(i=>i.required=!!defs[form.dataset.table].fields.find(f=>f[0]===i.name)?.[3])}
async function saveForm(form){const table=form.dataset.table;const fd=new FormData(form);const data={};for(const[n,,t]of defs[table].fields){if(t==='checkbox')data[n]=form.elements[n].checked;else if(t==='image'){const file=form.elements[n].files[0];if(file)data[n]=await upload(file,table)}else data[n]=fd.get(n)||null}data.creado_por=state.user.id;const id=form.id.value;let q;if(id){delete data.creado_por;if(!data.imagen_url)delete data.imagen_url;q=sb.from(table).update(data).eq('id',id)}else q=sb.from(table).insert(data);const{error}=await q;if(error)throw error;message('Contenido guardado correctamente.');resetForm(form);await loadTable(table)}
async function deleteRow(table,id){if(!confirm('¿Eliminar esta publicación?'))return;const{error}=await sb.from(table).delete().eq('id',id);if(error)return message(error.message,true);message('Publicación eliminada.');loadTable(table)}
async function loadAll(){for(const t of Object.keys(defs))await loadTable(t)}
$('login-form').onsubmit=async e=>{e.preventDefault();$('login-message').textContent='Ingresando...';const{error}=await sb.auth.signInWithPassword({email:$('login-email').value.trim(),password:$('login-password').value});if(error){const friendly=error.message==='Invalid login credentials'?'Correo o contraseña incorrectos. Puedes usar “Olvidé mi contraseña”.':error.message;$('login-message').textContent='No se pudo ingresar: '+friendly;return}$('login-message').textContent='';verify()};
const forgotBtn=$('forgot-password');if(forgotBtn)forgotBtn.onclick=async()=>{const email=$('login-email').value.trim();if(!email){$('login-message').textContent='Escribe primero tu correo electrónico.';return}const redirectTo=new URL('admin.html',window.location.href).href;const{error}=await sb.auth.resetPasswordForEmail(email,{redirectTo});$('login-message').textContent=error?'No se pudo enviar el enlace: '+error.message:'Te enviamos un enlace para crear una nueva contraseña. Revisa también la carpeta de correo no deseado.'};
const recoveryForm=$('recovery-form');if(recoveryForm)recoveryForm.onsubmit=async e=>{e.preventDefault();const a=$('new-password').value,b=$('confirm-password').value;if(a!==b){$('recovery-message').textContent='Las contraseñas no coinciden.';return}const{error}=await sb.auth.updateUser({password:a});if(error){$('recovery-message').textContent='No se pudo cambiar la contraseña: '+error.message;return}$('recovery-message').textContent='Contraseña actualizada. Ya puedes ingresar.';setTimeout(()=>{location.href='admin.html'},1200)};
const logoutBtn=$('logout-button');if(logoutBtn)logoutBtn.onclick=async()=>{await sb.auth.signOut();showLogin()};
document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-section]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.admin-section').forEach(s=>s.hidden=s.id!==`section-${b.dataset.section}`);$('page-title').textContent=b.textContent.trim()});
buildForms();document.querySelectorAll('form[data-table]').forEach(f=>{f.onsubmit=async e=>{e.preventDefault();try{await saveForm(f)}catch(err){message(err.message||String(err),true)}};f.querySelector('.cancel').onclick=()=>resetForm(f)});sb.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY'){$('login-form').hidden=true;$('recovery-form').hidden=false;$('login-message').textContent=''}else setTimeout(verify,0)});verify();
})();
