(function(){
const KEY='villa-el-trigal-content-v1';let items=[];
const $=id=>document.getElementById(id);const esc=v=>String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function load(){try{items=JSON.parse(localStorage.getItem(KEY)||'[]')}catch{items=[]}render()}
function save(){localStorage.setItem(KEY,JSON.stringify(items));render()}
function reset(){ $('announcement-form').reset();$('published').checked=true;$('item-id').value='';$('form-title').textContent='Nuevo anuncio';$('cancel-edit').hidden=true }
function render(){const today=new Date().toISOString().slice(0,10);$('count-all').textContent=items.length;$('count-active').textContent=items.filter(x=>x.published&&(!x.expires_at||x.expires_at>=today)).length;$('count-pinned').textContent=items.filter(x=>x.pinned).length;const list=$('items-list');if(!items.length){list.innerHTML='<div class="panel empty">Todavía no hay anuncios.</div>';return}list.innerHTML=items.sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).map(x=>`<article class="item"><div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><div class="item-meta">${esc(x.category)} · ${x.published?'Publicado':'Borrador'}${x.expires_at?' · Vence '+esc(x.expires_at):''}</div></div><div class="actions"><button class="button secondary" data-edit="${x.id}">Editar</button><button class="button danger" data-delete="${x.id}">Eliminar</button></div></article>`).join('')}
$('announcement-form').addEventListener('submit',e=>{e.preventDefault();const id=$('item-id').value||String(Date.now());const old=items.find(x=>x.id===id);const data={id,title:$('title').value.trim(),category:$('category').value,description:$('description').value.trim(),event_date:$('event-date').value,event_time:$('event-time').value,location:$('location').value.trim(),expires_at:$('expires-at').value,pinned:$('pinned').checked,published:$('published').checked,created_at:old?.created_at||new Date().toISOString()};items=items.filter(x=>x.id!==id);items.push(data);save();reset()});
$('items-list').addEventListener('click',e=>{const edit=e.target.dataset.edit,del=e.target.dataset.delete;if(del&&confirm('¿Eliminar este anuncio?')){items=items.filter(x=>x.id!==del);save()}if(edit){const x=items.find(i=>i.id===edit);if(!x)return;$('item-id').value=x.id;$('title').value=x.title;$('category').value=x.category;$('description').value=x.description;$('event-date').value=x.event_date||'';$('event-time').value=x.event_time||'';$('location').value=x.location||'';$('expires-at').value=x.expires_at||'';$('pinned').checked=!!x.pinned;$('published').checked=x.published!==false;$('form-title').textContent='Editar anuncio';$('cancel-edit').hidden=false;scrollTo({top:0,behavior:'smooth'})}});
$('cancel-edit').addEventListener('click',reset);$('export-button').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(items,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='respaldo-anuncios-villa-el-trigal.json';a.click();URL.revokeObjectURL(a.href)});load();
})();
