/* SIGVE v1.1.1 · Certificados manuales y autoridades */
(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const cfg=window.PORTAL_CONFIG||{};
const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=v=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(v)||0);
const dateCL=v=>v?new Date(v+'T12:00:00').toLocaleDateString('es-CL'):'—';
const today=()=>new Date().toISOString().slice(0,10);
const cleanRut=v=>String(v||'').replace(/[^0-9kK]/g,'').toUpperCase();
const formatRut=v=>{const c=cleanRut(v);if(c.length<2)return c;let b=c.slice(0,-1),dv=c.slice(-1),o='';while(b.length>3){o='.'+b.slice(-3)+o;b=b.slice(0,-3)}return b+o+'-'+dv};
const validRut=v=>{const c=cleanRut(v);if(c.length<7)return false;const b=c.slice(0,-1),dv=c.slice(-1);let sum=0,m=2;for(let i=b.length-1;i>=0;i--){sum+=Number(b[i])*m;m=m===7?2:m+1}const r=11-(sum%11),e=r===11?'0':r===10?'K':String(r);return dv===e};
const phoneDigits111=v=>{let d=String(v||'').replace(/\D/g,'');if(d.startsWith('569'))d=d.slice(3);else if(d.startsWith('56')){d=d.slice(2);if(d.startsWith('9'))d=d.slice(1)}else if(d.length===9&&d.startsWith('9'))d=d.slice(1);return d.slice(0,8)};
const formatPhone111=v=>{const d=phoneDigits111(v);return d?`+56 9 ${d.slice(0,4)}${d.length>4?' '+d.slice(4):''}`:''};
const phoneDb111=v=>{const d=phoneDigits111(v);return d.length===8?`+569${d}`:null};


function toast(t,err=false){const el=$('#global-message');if(el){el.textContent=t;el.classList.toggle('error',err);setTimeout(()=>{if(el.textContent===t)el.textContent=''},6000)}else alert(t)}
function modal(html){const d=document.createElement('dialog');d.className='v7-modal';d.innerHTML=`<div class="v7-modal-card">${html}</div>`;document.body.appendChild(d);d.showModal();d.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>d.remove());d.addEventListener('cancel',()=>d.remove());return d}

let certs=[];
async function loadCerts111(){const{data,error}=await sb.from('certificados_emitidos').select('*').order('folio',{ascending:false}).limit(500);if(error)return toast('Certificados: '+error.message,true);certs=data||[];renderCerts111()}
function renderCerts111(){const q=($('#cert-search')?.value||'').toLowerCase();const rows=certs.filter(x=>`${x.folio||''} ${x.nombre||''} ${x.rut||''}`.toLowerCase().includes(q));const paid=certs.filter(x=>x.estado_pago==='pagado');$('#cert-summary').innerHTML=`<div class="stat"><span>Registrados</span><strong>${certs.length}</strong></div><div class="stat"><span>Pagados</span><strong>${paid.length}</strong></div><div class="stat"><span>Pendientes</span><strong>${certs.filter(x=>x.estado_pago==='pendiente').length}</strong></div><div class="stat"><span>Recaudado</span><strong>${money(paid.reduce((a,x)=>a+Number(x.valor),0))}</strong></div>`;
$('#cert-body').innerHTML=rows.map(x=>`<tr><td><strong>${String(x.folio||0).padStart(5,'0')}</strong></td><td>${dateCL(x.fecha)}</td><td>${esc(x.nombre)}<br><small>${esc(x.rut)}</small><br><small>${x.origen_solicitud==='portal_socio'?'👤 Portal Socio':x.origen_solicitud==='publico'?'🌐 Portal público':'⚙️ Administración'}</small></td><td>${esc(x.direccion)}</td><td><span class="v110-status ${esc(x.estado_pago)}">${esc(x.estado_pago)}</span><br><small>${esc(x.estado_documento||'emitido')}</small></td><td>${money(x.valor)}</td><td><div class="cert-actions"><button class="button secondary" data-edit-cert="${x.id}">Editar</button><button class="button secondary" data-print-cert111="${x.id}">Generar digital</button></div></td></tr>`).join('')||'<tr><td colspan="7">Sin certificados.</td></tr>';
$$('[data-edit-cert]').forEach(b=>b.onclick=()=>openCert(certs.find(x=>x.id===b.dataset.editCert)));
$$('[data-print-cert111]').forEach(b=>b.onclick=()=>printCert111(certs.find(x=>x.id===b.dataset.printCert111)));
}
async function openCert(x=null){
  const [st,so,folioRes]=await Promise.all([
    sb.from('configuracion_gestion').select('*').eq('id',1).single(),
    sb.from('socios').select('id,numero_socio,nombre_completo,rut,nacionalidad,direccion,telefono,correo').eq('estado','activo').order('nombre_completo'),
    x?Promise.resolve({data:x.folio}):sb.from('certificados_emitidos').select('folio').order('folio',{ascending:false}).limit(1).maybeSingle()
  ]);
  if(st.error)return toast(st.error.message,true);
  const nextFolio=x?.folio||Number(folioRes.data?.folio||0)+1;
  const opts=(so.data||[]).map(s=>`<option value="${s.id}" ${x?.socio_id===s.id?'selected':''}>${esc(s.nombre_completo)} · N° ${s.numero_socio||'—'}</option>`).join('');
  const d=modal(`<h3>Emitir certificado de residencia</h3><form><div class="v7-grid">
    <label>Vincular socio<select name="socio"><option value="">No es socio / ingreso manual</option>${opts}</select></label>
    <label>Fecha<input name="fecha" type="date" value="${x?.fecha||today()}" required></label>
    <label>Número correlativo<input name="folioView" value="CR-${String(nextFolio).padStart(5,'0')}" readonly><input name="folio" type="hidden" value="${nextFolio}"></label>
    <label>Nombre completo<input name="nombre" value="${esc(x?.nombre||'')}" required></label>
    <label>Nacionalidad<input name="nacionalidad" value="${esc(x?.nacionalidad||'')}" required></label>
    <label>RUT<input name="rut" inputmode="text" maxlength="12" placeholder="12.345.678-9" value="${esc(x?.rut||'')}" required></label>
    <label>Dirección<input name="direccion" value="${esc(x?.direccion||'')}" required></label>
    <label>Teléfono<input name="telefono" inputmode="numeric" maxlength="16" placeholder="+56 9 1234 5678" value="${esc(formatPhone111(x?.telefono||''))}"></label>
    <label>Correo electrónico<input name="correo" type="email" value="${esc(x?.correo||'')}"></label>
    <label>Finalidad<select name="finalidad"><option value="laboral">Laboral</option><option value="estudiantil">Estudiantil</option><option value="transporte">Transporte</option><option value="otro">Otro</option></select></label>
    <label data-purpose-other hidden>Especificar otra finalidad<input name="finalidad_otro" maxlength="160" value="${esc(x?.finalidad_otro||'')}"></label>
    <label>Estado documental<select name="estado_documento"><option value="pendiente_emision">Pendiente de emisión</option><option value="emitido">Emitido</option><option value="anulado">Anulado</option></select></label>
    <label>Estado de pago<select name="estado_pago"><option value="pendiente">Pendiente</option><option value="pagado">Pagado</option><option value="exento">Exento</option><option value="anulado">Anulado</option></select></label>
    <label>Valor<input name="valor" type="number" min="0" value="${x?.valor??st.data.valor_certificado}" required></label>
    <label>Medio<select name="medio"><option value="efectivo">Efectivo</option><option value="transferencia">Transferencia</option></select></label>
    <label>Fondo<select name="fondo"><option value="caja">Caja chica</option><option value="banco">Cuenta bancaria</option></select></label>
  </div><div class="actions"><button class="button primary">Guardar</button><button type="button" class="button secondary" data-close>Cancelar</button></div></form>`);
  const f=d.querySelector('form'),otherWrap=d.querySelector('[data-purpose-other]');f.telefono.addEventListener('input',()=>f.telefono.value=formatPhone111(f.telefono.value));
  f.finalidad.value=x?.finalidad||'laboral';f.estado_documento.value=x?.estado_documento||'emitido';f.estado_pago.value=x?.estado_pago||'pendiente';f.medio.value=x?.medio_pago||'efectivo';f.fondo.value=x?.fondo||'caja';
  const toggleOther=()=>{const show=f.finalidad.value==='otro';otherWrap.hidden=!show;f.finalidad_otro.required=show;if(!show)f.finalidad_otro.value=''};toggleOther();f.finalidad.onchange=toggleOther;
  f.rut.addEventListener('input',()=>f.rut.value=formatRut(f.rut.value));
  f.socio.onchange=()=>{const socio=(so.data||[]).find(y=>y.id===f.socio.value);if(socio){f.nombre.value=socio.nombre_completo;f.nacionalidad.value=socio.nacionalidad||'';f.rut.value=formatRut(socio.rut);f.direccion.value=socio.direccion||'';f.telefono.value=formatPhone111(socio.telefono||'');f.correo.value=socio.correo||''}};
  f.medio.onchange=()=>f.fondo.value=f.medio.value==='transferencia'?'banco':'caja';
  f.onsubmit=async e=>{e.preventDefault();f.rut.value=formatRut(f.rut.value);if(!validRut(f.rut.value))return toast('El RUT ingresado no es válido.',true);const phone=phoneDb111(f.telefono.value);if(f.telefono.value&&!phone)return toast('Ingresa un celular chileno válido: +56 9 1234 5678.',true);if(f.finalidad.value==='otro'&&!f.finalidad_otro.value.trim())return toast('Especifica la otra finalidad.',true);
    const common={p_folio:Number(f.folio.value),p_nombre:f.nombre.value,p_rut:f.rut.value,p_nacionalidad:f.nacionalidad.value.trim(),p_direccion:f.direccion.value,p_finalidad:f.finalidad.value,p_finalidad_otro:f.finalidad_otro.value,p_fecha:f.fecha.value,p_valor:Number(f.valor.value),p_estado_documento:f.estado_documento.value,p_estado_pago:f.estado_pago.value,p_medio:f.medio.value,p_fondo:f.fondo.value,p_referencia:'',p_observaciones:''};
    const call=x?['actualizar_certificado_v111',{p_id:x.id,...common}]:['registrar_certificado_v111',{p_socio_id:f.socio.value||null,...common}];
    const{data,error}=await sb.rpc(call[0],call[1]);if(error)return toast(error.message,true);
    const certId=x?.id||data;const upd=await sb.from('certificados_emitidos').update({telefono:phone,correo:f.correo.value.trim().toLowerCase()||null,nacionalidad:f.nacionalidad.value.trim()||null,destino:null,referencia_transferencia:null,observaciones:null}).eq('id',certId);if(upd.error)return toast(upd.error.message,true);
    d.remove();toast(x?'Certificado actualizado.':'Certificado registrado.');loadCerts111();
  };
}

async function getDocConfig(){const[{data:conf},{data:auths}]=await Promise.all([sb.from('configuracion_documentos').select('*').eq('id',1).single(),sb.from('autoridades_junta').select('*').eq('activo',true)]);return{conf:conf||{},auths:auths||[]}}
async function printCert111(x){const{conf,auths}=await getDocConfig();if(conf.certificado_digital_habilitado===false&&!confirm('La generación digital está deshabilitada en configuración. ¿Deseas generar una vista previa de todas formas?'))return;const cargos=['secretario','presidente','tesorero'].filter(c=>conf[`firma_${c}`]);const signatureHtml=cargos.map(c=>{const a=auths.find(y=>y.cargo===c);return a?`<div class="cert-signature">${a.firma_data_url?`<img src="${a.firma_data_url}">`:''}<div class="line"><strong>${esc(a.nombre_completo)}</strong><br>${c[0].toUpperCase()+c.slice(1)}(a)</div></div>`:''}).join('');const checks={laboral:'',estudiantil:'',transporte:'',otro:''};checks[x.finalidad||'otro']='✓';const w=window.open('','_blank');w.document.write(`<html><head><title>Certificado ${x.folio}</title><link rel="stylesheet" href="admin-v111.css"></head><body><div class="cert-print-sheet"><div class="cert-print-header"><img src="assets/logo.svg"><div class="cert-print-title"><h1>JUNTA DE VECINOS VILLA EL TRIGAL</h1><h2>CERTIFICADO DE RESIDENCIA</h2></div><div class="cert-print-folio">Folio N° ${String(x.folio).padStart(5,'0')}<br>Valor ${money(x.valor)}</div></div><div class="cert-print-body"><p>La Junta de Vecinos Villa El Trigal certifica que don(ña) <strong>${esc(x.nombre)}</strong>, de nacionalidad <strong>${esc(x.nacionalidad||'no informada')}</strong>, RUT <strong>${esc(x.rut)}</strong>, tiene domicilio en <strong>${esc(x.direccion)}</strong>.</p><p>Se extiende el presente certificado a petición de la persona interesada para los fines indicados:</p><div class="cert-purpose"><span>${checks.laboral} Laboral</span><span>${checks.estudiantil} Estudiantil</span><span>${checks.transporte} Transporte</span><span>${checks.otro} Otro</span></div>${x.finalidad==='otro'&&x.finalidad_otro?`<p><strong>Otro:</strong> ${esc(x.finalidad_otro)}</p>`:''}<p>San Antonio, ${dateCL(x.fecha)}.</p></div><div class="cert-signatures">${signatureHtml||'<div class="cert-signature"><div class="line">Firma y timbre</div></div>'}</div></div><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}

async function loadAuthorities(){const{data,error}=await sb.from('autoridades_junta').select('*').order('activo',{ascending:false}).order('cargo');if(error)return toast(error.message,true);$('#authorities-list').innerHTML=(data||[]).map(a=>`<div class="authority-card"><div><strong>${esc(a.nombre_completo)}</strong> · ${esc(a.cargo)}${a.activo?' · Vigente':' · Histórico'}<small>${a.periodo_desde?dateCL(a.periodo_desde):'Sin fecha'} — ${a.periodo_hasta?dateCL(a.periodo_hasta):'Actual'}</small>${a.firma_data_url?`<img class="signature-preview" src="${a.firma_data_url}">`:''}</div><div><button class="button secondary" data-edit-authority="${a.id}">Editar</button></div></div>`).join('')||'<p>No hay autoridades registradas.</p>';$$('[data-edit-authority]').forEach(b=>b.onclick=()=>editAuthority((data||[]).find(a=>a.id===b.dataset.editAuthority)));const{data:conf}=await sb.from('configuracion_documentos').select('*').eq('id',1).single();if(conf){const f=$('#document-config-form');f.certificado_digital_habilitado.checked=conf.certificado_digital_habilitado;f.firma_presidente.checked=conf.firma_presidente;f.firma_secretario.checked=conf.firma_secretario;f.firma_tesorero.checked=conf.firma_tesorero}}
function fileData(file){return new Promise((resolve,reject)=>{if(!file)return resolve(null);if(file.size>700000)return reject(new Error('La imagen debe pesar menos de 700 KB'));const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
async function editAuthority(a=null){const d=modal(`<h3>${a?'Editar':'Nueva'} autoridad</h3><form><div class="v7-grid"><label>Cargo<select name="cargo"><option value="presidente">Presidente(a)</option><option value="secretario">Secretario(a)</option><option value="tesorero">Tesorero(a)</option><option value="otro">Otro</option></select></label><label>Nombre completo<input name="nombre" value="${esc(a?.nombre_completo||'')}" required></label><label>Desde<input name="desde" type="date" value="${a?.periodo_desde||''}"></label><label>Hasta<input name="hasta" type="date" value="${a?.periodo_hasta||''}"></label><label>Firma (foto PNG/JPG)<input name="firma" type="file" accept="image/png,image/jpeg"></label><label class="check"><input name="activo" type="checkbox" ${a?.activo!==false?'checked':''}> Autoridad vigente</label></div>${a?.firma_data_url?`<img class="signature-preview" src="${a.firma_data_url}">`:''}<div class="actions"><button class="button primary">Guardar</button><button type="button" class="button secondary" data-close>Cancelar</button></div></form>`);const f=d.querySelector('form');f.telefono.addEventListener('input',()=>f.telefono.value=formatPhone111(f.telefono.value));f.cargo.value=a?.cargo||'presidente';f.onsubmit=async e=>{e.preventDefault();let firma;try{firma=await fileData(f.firma.files[0])}catch(err){return toast(err.message,true)}const row={cargo:f.cargo.value,nombre_completo:f.nombre.value,periodo_desde:f.desde.value||null,periodo_hasta:f.hasta.value||null,activo:f.activo.checked,actualizado_en:new Date().toISOString(),firma_data_url:firma||a?.firma_data_url||null};if(row.activo&&['presidente','secretario','tesorero'].includes(row.cargo))await sb.from('autoridades_junta').update({activo:false,periodo_hasta:row.periodo_desde||today()}).eq('cargo',row.cargo).eq('activo',true).neq('id',a?.id||'00000000-0000-0000-0000-000000000000');const res=a?await sb.from('autoridades_junta').update(row).eq('id',a.id):await sb.from('autoridades_junta').insert({...row,creado_en:new Date().toISOString()});if(res.error)return toast(res.error.message,true);d.remove();toast('Autoridad guardada.');loadAuthorities()}}

function bind(){const nav=$('.sidebar nav');if(nav&&!nav.querySelector('[data-section="autoridades"]')){const directiva=nav.querySelector('[data-section="directiva"]');directiva?.insertAdjacentHTML('afterend','<button data-section="autoridades">✍️ Autoridades y firmas</button>')}$('#new-certificado').textContent='＋ Registrar certificado manual';$('#new-certificado').onclick=()=>openCert();$('#cert-search').oninput=renderCerts111;$('#new-authority').onclick=()=>editAuthority();$('#document-config-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;const{error}=await sb.from('configuracion_documentos').update({certificado_digital_habilitado:f.certificado_digital_habilitado.checked,firma_presidente:f.firma_presidente.checked,firma_secretario:f.firma_secretario.checked,firma_tesorero:f.firma_tesorero.checked,actualizado_en:new Date().toISOString()}).eq('id',1);if(error)return toast(error.message,true);toast('Configuración de documentos guardada.')};document.addEventListener('click',e=>{const b=e.target.closest('[data-section]');if(!b)return;if(b.dataset.section==='autoridades'){e.stopImmediatePropagation();$$('[data-section]').forEach(x=>x.classList.toggle('active',x===b));$$('.admin-section').forEach(s=>s.hidden=s.id!=='section-autoridades');$('#page-title').textContent='Autoridades y firmas';loadAuthorities()}if(b.dataset.section==='certificados')setTimeout(loadCerts111,80)},true)}
window.addEventListener('DOMContentLoaded',bind);
})();
