/* SIGVE v5.0.0 · Programa de Beneficios */
(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const cfg=window.PORTAL_CONFIG||{},sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=v=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(v)||0);
const dateCL=v=>v?new Date(v).toLocaleDateString('es-CL'):'—';
function toast(t,e=false){const el=$('#global-message');if(el){el.textContent=t;el.classList.toggle('error',e);setTimeout(()=>{if(el.textContent===t)el.textContent=''},5500)}else alert(t)}
function modal(html){const d=document.createElement('dialog');d.className='v7-modal';d.innerHTML=`<div class="v7-modal-card">${html}</div>`;document.body.appendChild(d);d.showModal();d.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>d.remove());d.addEventListener('cancel',()=>d.remove());return d}
let configs=[];
function addMenu(){const nav=$('.sidebar nav');if(!nav||nav.querySelector('[data-section="beneficios"]'))return;const b=document.createElement('button');b.type='button';b.dataset.section='beneficios';b.textContent='🎁 Beneficios';const reservas=nav.querySelector('[data-section="reservas-v7"]');reservas?reservas.insertAdjacentElement('afterend',b):nav.appendChild(b)}
async function load(){const [c,u]=await Promise.all([sb.from('beneficios_config').select('*').order('prioridad'),sb.from('beneficios_usos').select('*,socios(nombre_completo,numero_socio),reservas_sede(fecha_evento,estado)').order('creado_en',{ascending:false}).limit(100)]);if(c.error){$('#beneficios-list').innerHTML='<div class="panel">Ejecuta primero el SQL de SIGVE v5.0.</div>';return toast(c.error.message,true)}configs=c.data||[];render();const body=$('#beneficios-uses-body');if(body){body.innerHTML=(u.data||[]).map(x=>{const reverted=x.estado==='revertido';const status=reverted?`<span class="v7-badge">↩️ Revertido</span>${x.revertido_en?`<br><small>${dateCL(x.revertido_en)} · ${esc(x.motivo_reversion||'Cancelación de reserva')}</small>`:''}`:'<span class="v7-badge">✅ Aplicado</span>';const action=reverted?`<button class="button danger" data-delete-benefit-use="${x.id}">Eliminar de bitácora</button>`:'—';return `<tr><td>${dateCL(x.creado_en)}</td><td>${esc(x.socios?.nombre_completo||'—')}<br><small>N° ${esc(x.socios?.numero_socio||'—')}</small></td><td>${esc(x.beneficio_nombre)}<br>${status}</td><td>${x.reservas_sede?.fecha_evento?dateCL(x.reservas_sede.fecha_evento):'—'}</td><td>${money(x.valor_original)}</td><td>${money(x.valor_final)}</td><td>${action}</td></tr>`}).join('')||'<tr><td colspan="7">Aún no se han aplicado beneficios.</td></tr>';body.querySelectorAll('[data-delete-benefit-use]').forEach(b=>b.onclick=async()=>{if(!confirm('¿Eliminar este registro revertido de la bitácora? La reserva no será modificada.'))return;const{error}=await sb.rpc('eliminar_uso_beneficio_revertido',{p_uso_id:b.dataset.deleteBenefitUse});if(error)return toast(error.message,true);toast('Registro eliminado de la bitácora.');load()})}}
function render(){const host=$('#beneficios-list');if(!host)return;host.innerHTML=configs.map(x=>`<article class="beneficio-card"><span class="badge ${x.activo?'':'off'}">${x.activo?'ACTIVO':'DESACTIVADO'}</span><h4>${esc(x.nombre)}</h4><p>${esc(x.descripcion||'')}</p><div class="benefit-summary"><div><span>Cuotas requeridas</span><strong>${x.cuotas_minimas}</strong></div><div><span>Sin deuda vencida</span><strong>${x.exigir_sin_deuda?'Sí':'No'}</strong></div><div><span>Tipo</span><strong>${x.tipo==='gratis'?'1 arriendo gratis':x.tipo==='porcentaje'?'Descuento porcentual':'Descuento fijo'}</strong></div><div><span>Valor</span><strong>${x.tipo==='porcentaje'?x.valor+'%':x.tipo==='fijo'?money(x.valor):'1 uso/año'}</strong></div></div><div class="actions"><button class="button primary" data-benefit-edit="${x.id}">Editar</button><button class="button secondary" data-benefit-toggle="${x.id}">${x.activo?'Desactivar':'Activar'}</button></div></article>`).join('');$$('[data-benefit-edit]').forEach(b=>b.onclick=()=>edit(configs.find(x=>x.id===b.dataset.benefitEdit)));$$('[data-benefit-toggle]').forEach(b=>b.onclick=()=>toggle(configs.find(x=>x.id===b.dataset.benefitToggle)))}
function edit(x){const d=modal(`<h3>Editar beneficio</h3><form><div class="v7-grid"><label>Nombre<input name="nombre" value="${esc(x.nombre)}" required></label><label>Cuotas mínimas del año<input name="cuotas" type="number" min="0" max="12" value="${x.cuotas_minimas}" required></label><label>Tipo<select name="tipo"><option value="porcentaje">Descuento porcentual</option><option value="fijo">Descuento fijo</option><option value="gratis">1 arriendo gratis al año</option></select></label><label>Valor<input name="valor" type="number" min="0" value="${x.valor||0}"></label><label>Usos máximos por año<input name="usos" type="number" min="1" value="${x.usos_maximos_anuales||1}"></label><label class="check"><input name="sin_deuda" type="checkbox" ${x.exigir_sin_deuda?'checked':''}> Exigir que no tenga cuotas vencidas</label><label class="check"><input name="activo" type="checkbox" ${x.activo?'checked':''}> Beneficio activo</label><label class="wide">Descripción<textarea name="descripcion">${esc(x.descripcion||'')}</textarea></label><label class="wide">Fundamento o acuerdo<textarea name="acuerdo">${esc(x.acuerdo_directiva||'')}</textarea></label></div><div class="actions"><button class="button primary">Guardar</button><button type="button" class="button secondary" data-close>Cancelar</button></div></form>`);const f=d.querySelector('form');f.tipo.value=x.tipo;const sync=()=>{const free=f.tipo.value==='gratis';f.valor.closest('label').hidden=free;f.usos.closest('label').hidden=!free};f.tipo.onchange=sync;sync();f.onsubmit=async e=>{e.preventDefault();const row={nombre:f.nombre.value.trim(),descripcion:f.descripcion.value.trim()||null,cuotas_minimas:+f.cuotas.value,exigir_sin_deuda:f.sin_deuda.checked,tipo:f.tipo.value,valor:f.tipo.value==='gratis'?0:+f.valor.value,usos_maximos_anuales:f.tipo.value==='gratis'?+f.usos.value:999,activo:f.activo.checked,acuerdo_directiva:f.acuerdo.value.trim()||null,actualizado_en:new Date().toISOString()};const {error}=await sb.from('beneficios_config').update(row).eq('id',x.id);if(error)return toast(error.message,true);d.remove();toast('Beneficio actualizado.');load()}}
async function toggle(x){const{error}=await sb.from('beneficios_config').update({activo:!x.activo,actualizado_en:new Date().toISOString()}).eq('id',x.id);error?toast(error.message,true):load()}
function openSection(b){$$('[data-section]').forEach(x=>x.classList.toggle('active',x===b));$$('.admin-section').forEach(s=>s.hidden=s.id!=='section-beneficios');$('#page-title').textContent='🎁 Programa de Beneficios';setTimeout(load,40)}
async function enhanceReservation(d){if(d.dataset.benefitsEnhanced)return;const f=d.querySelector('form');if(!f||!f.elements.valor||!f.elements.rut)return;d.dataset.benefitsEnhanced='1';const rental=f.querySelector('.rental-only');if(!rental)return;const wrap=document.createElement('label');wrap.className='rental-only wide';wrap.innerHTML='<span>Socio para evaluar beneficio</span><select name="beneficio_socio"><option value="">Sin vincular / precio normal</option></select><div id="benefit-eval-box" class="help">Selecciona un socio para revisar sus beneficios.</div>';rental.parentNode.insertBefore(wrap,rental);const q=await sb.from('socios').select('id,numero_socio,nombre_completo,rut').eq('estado','activo').order('nombre_completo');if(q.error)return;f.beneficio_socio.innerHTML='<option value="">Sin vincular / precio normal</option>'+q.data.map(s=>`<option value="${s.id}">${esc(s.nombre_completo)} · N° ${esc(s.numero_socio||'—')}</option>`).join('');const base=Number(f.valor.value)||0;f.dataset.valorOriginal=String(base);f.beneficio_socio.onchange=async()=>{const box=d.querySelector('#benefit-eval-box'),sid=f.beneficio_socio.value;f.valor.value=f.dataset.valorOriginal;f.dataset.beneficioId='';f.dataset.beneficioNombre='';if(!sid){box.className='help';box.textContent='Precio normal, sin beneficio aplicado.';return}box.textContent='Evaluando cuotas…';const {data,error}=await sb.rpc('evaluar_beneficios_socio',{p_socio_id:sid,p_fecha:f.fecha.value||new Date().toISOString().slice(0,10),p_valor_original:Number(f.dataset.valorOriginal)});if(error){box.className='benefit-evaluation warn';box.textContent=error.message;return}const eligible=(data||[]).filter(x=>x.cumple);if(!eligible.length){box.className='benefit-evaluation warn';box.textContent=(data||[])[0]?.motivo||'El socio todavía no cumple los requisitos.';return}const best=eligible[0];f.dataset.beneficioId=best.beneficio_id;f.dataset.beneficioNombre=best.nombre;f.dataset.valorFinal=best.valor_final;f.valor.value=best.valor_final;box.className='benefit-evaluation';box.innerHTML=`<strong>✅ ${esc(best.nombre)}</strong><br>${esc(best.detalle)}<br>Valor normal: ${money(base)} · <strong>Total: ${money(best.valor_final)}</strong>`};f.fecha.addEventListener('change',()=>f.beneficio_socio.dispatchEvent(new Event('change')))}
function watchModals(){new MutationObserver(ms=>ms.forEach(m=>m.addedNodes.forEach(n=>{if(n.nodeType===1&&n.matches?.('dialog.v7-modal'))setTimeout(()=>enhanceReservation(n),40)}))).observe(document.body,{childList:true})}
function bind(){addMenu();$('#beneficios-refresh')?.addEventListener('click',load);document.addEventListener('click',e=>{const b=e.target.closest('[data-section="beneficios"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();openSection(b)},true);watchModals()}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',bind):bind();
window.SIGVEBeneficios={load,getReservationMeta(form){return {socio_id:form?.beneficio_socio?.value||null,beneficio_id:form?.dataset?.beneficioId||null,beneficio_nombre:form?.dataset?.beneficioNombre||null,valor_original:Number(form?.dataset?.valorOriginal||form?.valor?.value||0),valor_final:Number(form?.valor?.value||0)}}};
})();
