/* SIGVE v4.1.1 · Caja de Cuotas */
(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const cfg=window.PORTAL_CONFIG||{};
const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=v=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(v)||0);
const today=()=>{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santiago',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),v=Object.fromEntries(parts.map(x=>[x.type,x.value]));return `${v.year}-${v.month}-${v.day}`};
const month=v=>{if(!v)return '';const [y,m]=v.slice(0,7).split('-');return new Date(+y,+m-1,1).toLocaleDateString('es-CL',{month:'long',year:'numeric'})};
let rows=[],cashRequests=[];
function toast(text,error=false){const el=$('#global-message');if(el){el.textContent=text;el.classList.toggle('error',error);setTimeout(()=>{if(el.textContent===text)el.textContent=''},5000)}else alert(text)}
function modal(html){const d=document.createElement('dialog');d.className='v7-modal';d.innerHTML=`<div class="v7-modal-card">${html}</div>`;document.body.appendChild(d);d.showModal();d.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>d.remove());d.addEventListener('cancel',()=>d.remove());return d}
function addMenu(){const nav=$('.sidebar nav');if(!nav||nav.querySelector('[data-section="caja-cuotas"]'))return;const btn=document.createElement('button');btn.type='button';btn.dataset.section='caja-cuotas';btn.textContent='💵 Caja de Cuotas';const cuotas=nav.querySelector('[data-section="cuotas"]');const portal=nav.querySelector('a[href="index.html"]');if(cuotas)nav.insertBefore(btn,cuotas);else if(portal)nav.insertBefore(btn,portal);else nav.appendChild(btn)}
async function load(){const list=$('#caja-cuotas-list');if(!list)return;list.innerHTML='<div class="panel">Cargando socios con cuotas pendientes…</div>';const [q,r]=await Promise.all([sb.from('cuotas_socios').select('id,socio_id,periodo,monto,estado,socios(id,numero_socio,nombre_completo,rut)').eq('estado','pendiente').order('periodo',{ascending:true}),sb.from('solicitudes_pago_efectivo').select('id,socio_id,cuota_ids,monto_total,estado,creada_en').eq('estado','pendiente').order('creada_en',{ascending:false})]);if(q.error){list.innerHTML='<div class="panel">No fue posible cargar las cuotas.</div>';return toast(q.error.message,true)}rows=q.data||[];cashRequests=r.error?[]:(r.data||[]);render()}
function grouped(){const map=new Map();for(const q of rows){const s=q.socios||{};if(!map.has(q.socio_id))map.set(q.socio_id,{socio:s,cuotas:[]});map.get(q.socio_id).cuotas.push(q)}return [...map.values()].sort((a,b)=>Number(a.socio.numero_socio||999999)-Number(b.socio.numero_socio||999999))}
function render(){const term=($('#caja-cuotas-search')?.value||'').trim().toLowerCase();const groups=grouped().filter(g=>`${g.socio.numero_socio||''} ${g.socio.nombre_completo||''} ${g.socio.rut||''}`.toLowerCase().includes(term));const total=rows.reduce((a,x)=>a+Number(x.monto||0),0);$('#caja-cuotas-summary').innerHTML=`<div class="stat"><span>Socios pendientes</span><strong>${grouped().length}</strong></div><div class="stat"><span>Cuotas pendientes</span><strong>${rows.length}</strong></div><div class="stat"><span>Total por recaudar</span><strong>${money(total)}</strong></div>`;$('#caja-cuotas-list').innerHTML=groups.map(g=>{const sum=g.cuotas.reduce((a,x)=>a+Number(x.monto),0);return `<article class="caja-socio-card"><div class="caja-socio-head"><div><small>Socio N° ${esc(g.socio.numero_socio||'—')}</small><h4>${esc(g.socio.nombre_completo)}</h4><p>${esc(g.socio.rut||'')}</p>${cashRequests.some(r=>r.socio_id===g.socio.id)?'<span class="v7-badge status-pendiente">💵 Solicitó pago en efectivo</span>':''}</div><div class="caja-socio-total"><span>Deuda total</span><strong>${money(sum)}</strong></div></div><div class="caja-cuotas-options">${g.cuotas.map((q,i)=>`<label><input type="checkbox" data-caja-quota="${q.id}" data-socio="${q.socio_id}" ${i===0?'checked':''}><span>${esc(month(q.periodo))}</span><strong>${money(q.monto)}</strong></label>`).join('')}</div><div class="actions"><button class="button primary" data-caja-pay="${g.socio.id}">Registrar pago</button><button class="button secondary" data-caja-all="${g.socio.id}">Seleccionar todas</button></div></article>`}).join('')||'<div class="panel">No hay socios que coincidan con la búsqueda.</div>';$$('[data-caja-pay]').forEach(b=>b.onclick=()=>openPay(b.dataset.cajaPay));$$('[data-caja-all]').forEach(b=>b.onclick=()=>{const checks=$$(`[data-caja-quota][data-socio="${b.dataset.cajaAll}"]`);const all=checks.every(c=>c.checked);checks.forEach(c=>c.checked=!all)})}
function selectedFor(socioId){const ids=new Set($$(`[data-caja-quota][data-socio="${socioId}"]:checked`).map(c=>c.dataset.cajaQuota));return rows.filter(q=>ids.has(q.id))}
function openPay(socioId){const selected=selectedFor(socioId);if(!selected.length)return toast('Selecciona al menos una cuota.',true);const socio=selected[0].socios,total=selected.reduce((a,x)=>a+Number(x.monto),0),defaultMedium=cashRequests.some(r=>r.socio_id===socioId)?'efectivo':($('#caja-cuotas-default-medium')?.value||'efectivo');const d=modal(`<h3>Registrar pago de cuotas</h3><p><strong>${esc(socio.nombre_completo)}</strong> · Socio N° ${esc(socio.numero_socio||'—')}</p><div class="caja-review">${selected.map(q=>`<div><span>${esc(month(q.periodo))}</span><strong>${money(q.monto)}</strong></div>`).join('')}<div class="total"><span>Total</span><strong>${money(total)}</strong></div></div><form><div class="v7-grid"><label>Fecha<input name="fecha" type="date" value="${today()}" required></label><label>Medio de pago<select name="medio"><option value="efectivo" ${defaultMedium==='efectivo'?'selected':''}>Efectivo</option><option value="transferencia" ${defaultMedium==='transferencia'?'selected':''}>Transferencia</option></select></label><label>Destino<select name="fondo"><option value="caja">Caja chica</option><option value="banco">Cuenta bancaria</option></select></label><label>Referencia de transferencia<input name="referencia" placeholder="Opcional"></label><label class="wide">Observación<textarea name="observaciones" rows="2" placeholder="Opcional"></textarea></label></div><div class="actions"><button class="button primary">Confirmar e ingresar a Finanzas</button><button type="button" class="button secondary" data-close>Cancelar</button></div></form>`);const f=d.querySelector('form'),sync=()=>{f.fondo.value=f.medio.value==='transferencia'?'banco':'caja';f.referencia.closest('label').style.display=f.medio.value==='transferencia'?'':'none'};f.medio.onchange=sync;sync();f.onsubmit=async e=>{e.preventDefault();const ids=selected.map(q=>q.id);const {data,error}=await sb.rpc('registrar_pago_cuotas_caja',{p_cuota_ids:ids,p_fecha:f.fecha.value,p_medio:f.medio.value,p_fondo:f.fondo.value,p_referencia:f.referencia.value||null,p_observaciones:f.observaciones.value||null});if(error)return toast(error.message,true);d.remove();toast(`Pago confirmado: ${data||ids.length} cuota(s) asociadas al socio e ingresadas a Finanzas.`);await load();window.dispatchEvent(new CustomEvent('sigve:finanzas-actualizar'))}}
function openCajaSection(button){$$('[data-section]').forEach(x=>x.classList.toggle('active',x===button));$$('.admin-section').forEach(section=>section.hidden=section.id!=='section-caja-cuotas');const title=$('#page-title');if(title)title.textContent='💵 Caja de Cuotas';setTimeout(load,50)}
function bind(){addMenu();$('#caja-cuotas-search')?.addEventListener('input',render);$('#caja-cuotas-refresh')?.addEventListener('click',load);document.addEventListener('click',e=>{const b=e.target.closest('[data-section="caja-cuotas"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();openCajaSection(b)},true)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',bind):bind();
})();
