(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const cfg=window.PORTAL_CONFIG||{};
const sb=window.supabase?.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
let rows=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const dt=v=>v?new Intl.DateTimeFormat('es-CL',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—';
function toast(t,bad=false){const e=$('#global-message');if(!e)return alert(t);e.textContent=t;e.className='form-message '+(bad?'error':'success');setTimeout(()=>{e.textContent='';e.className='form-message'},4500)}
function install(){
 const nav=$('.sidebar nav'); if(nav&&!nav.querySelector('[data-section="inventario"]')) nav.insertAdjacentHTML('beforeend','<button data-section="inventario">📦 Inventario</button>');
 const main=$('.admin-main'); if(main&&!$('#section-inventario')) main.insertAdjacentHTML('beforeend',`<section id="section-inventario" class="admin-section" hidden>
 <div class="panel"><div class="panel-heading"><div><h3>📦 Inventario de la sede</h3><p class="help">Registra los bienes y equipamiento de la sede. La fecha de última actualización cambia automáticamente con cada modificación.</p></div><div class="actions"><button id="inv-new" class="button primary" type="button">＋ Agregar artículo</button><button id="inv-print" class="button secondary" type="button">🖨️ Imprimir inventario</button></div></div>
 <div class="inv-summary"><div class="stat"><span>Registros activos</span><strong id="inv-count">0</strong></div><div class="stat"><span>Total de unidades</span><strong id="inv-units">0</strong></div><div class="stat"><span>Última actualización</span><strong id="inv-updated">—</strong></div></div>
 <div class="v7-toolbar"><label>Buscar<input id="inv-search" placeholder="Artículo, categoría, ubicación..."></label><label>Estado<select id="inv-state"><option value="todos">Todos</option><option>Bueno</option><option>Regular</option><option>Malo</option></select></label><label><span>Mostrar bajas</span><select id="inv-active"><option value="activos">Solo activos</option><option value="todos">Todos</option><option value="bajas">Solo bajas</option></select></label></div></div>
 <div class="v7-table-wrap"><table class="v7-table"><thead><tr><th>Artículo</th><th>Categoría</th><th>Cantidad</th><th>Estado</th><th>Ubicación</th><th>Observaciones</th><th>Actualizado</th><th>Acción</th></tr></thead><tbody id="inv-body"><tr><td colspan="8">Cargando…</td></tr></tbody></table></div>
 </section>`);
 $('#inv-new').onclick=()=>edit(); $('#inv-print').onclick=printInventory; $('#inv-search').oninput=render; $('#inv-state').onchange=render; $('#inv-active').onchange=render;
 document.addEventListener('click',e=>{const b=e.target.closest('[data-section="inventario"]');if(!b)return;e.stopImmediatePropagation();$$('[data-section]').forEach(x=>x.classList.toggle('active',x===b));$$('.admin-section').forEach(s=>s.hidden=s.id!=='section-inventario');$('#page-title').textContent='📦 Inventario';load()},true);
 document.addEventListener('click',e=>{let b=e.target.closest('[data-inv-edit]');if(b){const x=rows.find(r=>String(r.id)===b.dataset.invEdit);if(x)edit(x)} b=e.target.closest('[data-inv-toggle]');if(b)toggle(b.dataset.invToggle)},true);
 }
async function load(){if(!sb)return;const {data,error}=await sb.from('inventario_sede').select('*').order('categoria').order('articulo');if(error){$('#inv-body').innerHTML='<tr><td colspan="8">No fue posible cargar el inventario. Ejecuta primero el SQL de actualización en Supabase.</td></tr>';return toast(error.message,true)}rows=data||[];render()}
function filtered(){const q=($('#inv-search')?.value||'').toLowerCase(),st=$('#inv-state')?.value||'todos',ac=$('#inv-active')?.value||'activos';return rows.filter(x=>(!q||[x.articulo,x.categoria,x.ubicacion,x.observaciones].some(v=>String(v||'').toLowerCase().includes(q)))&&(st==='todos'||x.estado===st)&&(ac==='todos'||(ac==='activos'?x.activo:!x.activo)))}
function render(){const list=filtered(),active=rows.filter(x=>x.activo),last=rows.map(x=>x.actualizado_en).filter(Boolean).sort().at(-1);$('#inv-count').textContent=active.length;$('#inv-units').textContent=active.reduce((a,x)=>a+Number(x.cantidad||0),0);$('#inv-updated').textContent=dt(last);$('#inv-body').innerHTML=list.map(x=>`<tr class="${x.activo?'':'inv-inactive'}"><td><strong>${esc(x.articulo)}</strong>${x.activo?'':'<br><small>BAJA</small>'}</td><td>${esc(x.categoria)}</td><td>${x.cantidad}</td><td><span class="inv-state inv-${String(x.estado).toLowerCase()}">${esc(x.estado)}</span></td><td>${esc(x.ubicacion||'—')}</td><td>${esc(x.observaciones||'—')}</td><td>${dt(x.actualizado_en)}</td><td><div class="actions"><button class="button secondary" data-inv-edit="${x.id}">Editar</button><button class="button ${x.activo?'danger':'secondary'}" data-inv-toggle="${x.id}">${x.activo?'Dar de baja':'Reactivar'}</button></div></td></tr>`).join('')||'<tr><td colspan="8">Sin artículos para mostrar.</td></tr>'}
function edit(x={}){const host=document.createElement('div');host.className='modal-backdrop';host.innerHTML=`<div class="modal-card inv-modal"><h3>${x.id?'Editar artículo':'Agregar artículo'}</h3><form><div class="form-grid"><label>Artículo<input name="articulo" required maxlength="120" value="${esc(x.articulo||'')}"></label><label>Categoría<input name="categoria" required maxlength="80" list="inv-cats" value="${esc(x.categoria||'Mobiliario')}"><datalist id="inv-cats"><option>Mobiliario</option><option>Electrodomésticos</option><option>Cocina</option><option>Baño</option><option>Aseo</option><option>Equipamiento</option><option>Infraestructura</option><option>Tecnología</option><option>Otros</option></datalist></label><label>Cantidad<input name="cantidad" type="number" min="0" step="1" required value="${x.cantidad??1}"></label><label>Estado<select name="estado">${['Bueno','Regular','Malo'].map(v=>`<option ${x.estado===v?'selected':''}>${v}</option>`)}</select></label><label>Ubicación<input name="ubicacion" maxlength="100" placeholder="Ej.: Salón principal" value="${esc(x.ubicacion||'')}"></label><label style="grid-column:1/-1">Observaciones<textarea name="observaciones" maxlength="500" placeholder="Detalles, marcas, daños previos, etc.">${esc(x.observaciones||'')}</textarea></label></div><div class="actions"><button class="button primary">Guardar</button><button class="button secondary" type="button" data-close-inv>Cancelar</button></div></form></div>`;document.body.appendChild(host);host.querySelector('[data-close-inv]').onclick=()=>host.remove();host.onclick=e=>{if(e.target===host)host.remove()};host.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,p={articulo:f.articulo.value.trim(),categoria:f.categoria.value.trim(),cantidad:+f.cantidad.value,estado:f.estado.value,ubicacion:f.ubicacion.value.trim()||null,observaciones:f.observaciones.value.trim()||null,actualizado_en:new Date().toISOString()};const r=x.id?await sb.from('inventario_sede').update(p).eq('id',x.id):await sb.from('inventario_sede').insert(p);if(r.error)return toast(r.error.message,true);host.remove();toast('Inventario actualizado.');load()}}
async function toggle(id){const x=rows.find(r=>String(r.id)===String(id));if(!x)return;if(!confirm(x.activo?'¿Dar de baja este artículo? El registro se conservará en el historial.':'¿Reactivar este artículo?'))return;const {error}=await sb.from('inventario_sede').update({activo:!x.activo,actualizado_en:new Date().toISOString()}).eq('id',id);if(error)return toast(error.message,true);toast(x.activo?'Artículo dado de baja.':'Artículo reactivado.');load()}
function printInventory(){const list=rows.filter(x=>x.activo),last=rows.map(x=>x.actualizado_en).filter(Boolean).sort().at(-1),w=window.open('','_blank');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Inventario Villa El Trigal</title><style>body{font-family:Arial,sans-serif;color:#111;margin:28px}h1,h2,p{text-align:center;margin:5px}table{width:100%;border-collapse:collapse;margin-top:20px;font-size:12px}th,td{border:1px solid #555;padding:7px;text-align:left}th{background:#eee}.meta{margin:18px 0;text-align:left}.foot{margin-top:35px;display:flex;justify-content:space-between}.sign{width:40%;border-top:1px solid #222;text-align:center;padding-top:5px}@media print{button{display:none}}</style></head><body><h2>JUNTA DE VECINOS VILLA EL TRIGAL</h2><h1>INVENTARIO DE SEDE SOCIAL</h1><p>Armando Sabaj Sabaj 1278</p><div class="meta"><strong>Última actualización:</strong> ${dt(last)}<br><strong>Registros:</strong> ${list.length} &nbsp; <strong>Total unidades:</strong> ${list.reduce((a,x)=>a+Number(x.cantidad||0),0)}</div><table><thead><tr><th>Artículo</th><th>Categoría</th><th>Cant.</th><th>Estado</th><th>Ubicación</th><th>Observaciones</th></tr></thead><tbody>${list.map(x=>`<tr><td>${esc(x.articulo)}</td><td>${esc(x.categoria)}</td><td>${x.cantidad}</td><td>${esc(x.estado)}</td><td>${esc(x.ubicacion||'')}</td><td>${esc(x.observaciones||'')}</td></tr>`).join('')}</tbody></table><div class="foot"><div class="sign">Responsable Junta de Vecinos</div><div class="sign">Fecha / firma</div></div><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
window.addEventListener('DOMContentLoaded',()=>setTimeout(install,80));
})();
