(()=>{'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const digits=v=>String(v||'').replace(/\D/g,'');
const cleanRut=v=>String(v||'').replace(/[^0-9kK]/g,'').toUpperCase();
const formatRut=v=>{const c=cleanRut(v);if(c.length<2)return c;let b=c.slice(0,-1),d=c.slice(-1),o='';while(b.length>3){o='.'+b.slice(-3)+o;b=b.slice(0,-3)}return b+o+'-'+d};
const age=d=>{if(!d)return'';const b=new Date(d+'T12:00:00'),n=new Date();let a=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||(n.getMonth()===b.getMonth()&&n.getDate()<b.getDate()))a--;return a>=0?a:''};
let sb,state;
function close(){document.querySelector('.navidad-modal-backdrop')?.remove()}
function modal(){const host=document.createElement('div');host.className='navidad-modal-backdrop';host.innerHTML=`<div class="navidad-modal"><div class="navidad-modal-head"><div><small>🎄 Navidad ${state.anio}</small><h2>Registrar niño o niña</h2></div><button class="navidad-close" aria-label="Cerrar">×</button></div><div class="navidad-note"><strong>Importante:</strong> si eres socio/a y el niño o niña ya está ingresado en SIGVE, no debes registrarlo nuevamente.</div><form id="navidad-form" class="navidad-grid"><label class="full">Nombre completo *<input name="nombre" required autocomplete="name"></label><label>RUT *<input name="rut" required placeholder="12.345.678-9"></label><label>Fecha de nacimiento *<input name="nacimiento" type="date" required></label><label>Edad<input name="edad" readonly placeholder="Se calcula automáticamente"></label><label class="full">Dirección *<input name="direccion" required placeholder="Calle / pasaje y número"></label><label class="full">Teléfono de contacto *<div class="public-phone"><span>+56 9</span><input name="telefono" data-phone required inputmode="numeric" placeholder="12345678"></div></label><div class="full navidad-actions"><button class="button primary" type="submit">Registrar</button><button class="button secondary" type="button" data-close>Cancelar</button></div><p class="full navidad-status" aria-live="polite"></p></form></div>`;document.body.append(host);host.querySelector('.navidad-close').onclick=close;host.querySelector('[data-close]').onclick=close;host.onclick=e=>{if(e.target===host)close()};const f=host.querySelector('form');const r=f.rut,n=f.nacimiento;r.oninput=()=>r.value=formatRut(r.value);n.onchange=()=>f.edad.value=age(n.value)===''?'':`${age(n.value)} años`;window.SIGVE_PHONE?.enhance(f.telefono);f.onsubmit=submit;}
async function submit(e){e.preventDefault();const f=e.currentTarget,st=f.querySelector('.navidad-status'),btn=f.querySelector('[type=submit]');const tel=window.SIGVE_PHONE?.getDbValue(f.telefono)||('+'+digits(f.telefono.value));if(!tel){st.className='full navidad-status err';st.textContent='Revisa el teléfono de contacto.';return}btn.disabled=true;st.textContent='Registrando…';try{const{data,error}=await sb.rpc('registrar_navidad_publica',{p_nombre:f.nombre.value.trim(),p_rut:f.rut.value,p_fecha_nacimiento:f.nacimiento.value,p_direccion:f.direccion.value.trim(),p_telefono:tel});if(error)throw error;if(data==='YA_SIGVE'){st.className='full navidad-status ok';st.textContent='Este niño o niña ya está registrado en SIGVE. No es necesario volver a inscribirlo.'}else if(data==='YA_EXTERNO'){st.className='full navidad-status ok';st.textContent=`Este niño o niña ya fue registrado para Navidad ${state.anio}.`}else{st.className='full navidad-status ok';st.textContent=`Registro realizado correctamente para Navidad ${state.anio}.`;f.reset();f.edad.value='';}}catch(x){st.className='full navidad-status err';st.textContent=x.message||'No fue posible registrar.'}finally{btn.disabled=false}}
async function init(){if(!window.supabase||!window.PORTAL_CONFIG)return;sb=window.supabase.createClient(window.PORTAL_CONFIG.supabaseUrl,window.PORTAL_CONFIG.supabaseAnonKey);const{data,error}=await sb.rpc('estado_navidad_publica');if(error||!data?.length)return;state=data[0];const block=$('#navidad-publica');if(!block)return;block.hidden=false;block.querySelector('[data-navidad-year]').textContent=state.anio;const status=block.querySelector('[data-navidad-status]'),btn=block.querySelector('[data-open-navidad]');if(state.abierto){status.textContent='Inscripciones abiertas.';btn.hidden=false;btn.onclick=modal;const key=`sigve-navidad-popup-${state.anio}`;if(!localStorage.getItem(key)){setTimeout(()=>{modal();localStorage.setItem(key,'1')},650)}}else{status.textContent='Las inscripciones no se encuentran abiertas en este momento.';btn.hidden=true}block.querySelector('[data-hazte-socio]').onclick=()=>{close();location.hash='socios-solicitud'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
