(()=>{'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const digits=v=>String(v||'').replace(/\D/g,'');
const cleanRut=v=>String(v||'').replace(/[^0-9kK]/g,'').toUpperCase();
const formatRut=v=>{const c=cleanRut(v);if(c.length<2)return c;let b=c.slice(0,-1),d=c.slice(-1),o='';while(b.length>3){o='.'+b.slice(-3)+o;b=b.slice(0,-3)}return b+o+'-'+d};
const age=d=>{if(!d)return'';const b=new Date(d+'T12:00:00'),n=new Date();let a=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||(n.getMonth()===b.getMonth()&&n.getDate()<b.getDate()))a--;return a>=0?a:''};
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const viaLabel=v=>`${v.tipo||''} ${v.nombre||''}`.trim();
let sb,state,vias=[];
function close(){document.querySelector('.navidad-modal-backdrop')?.remove()}
async function loadVias(){const{data,error}=await sb.from('vias').select('id,tipo,nombre,aliases').eq('activa',true).order('nombre');if(error)throw new Error('No fue posible cargar las calles y pasajes de Villa El Trigal.');vias=(data||[]).sort((a,b)=>viaLabel(a).localeCompare(viaLabel(b),'es',{sensitivity:'base'}));}
function bindVia(f){const root=f.querySelector('[data-navidad-via-picker]'),input=f.via_busqueda,hidden=f.via_id,list=root.querySelector('.via-suggestions'),number=f.numero_domicilio,preview=f.querySelector('[data-address-preview]');let matches=[];const update=()=>{const v=vias.find(x=>x.id===hidden.value);preview.textContent=v&&number.value.trim()?`📍 ${viaLabel(v)} ${number.value.trim()}`:'📍 Selecciona una vía registrada e ingresa el número.'};const closeList=()=>{list.hidden=true;input.setAttribute('aria-expanded','false')};const choose=v=>{hidden.value=v.id;input.value=viaLabel(v);root.classList.remove('invalid');closeList();update()};const render=()=>{const q=norm(input.value);hidden.value='';matches=vias.filter(v=>!q||norm([viaLabel(v),...(v.aliases||[])].join(' ')).includes(q)).slice(0,30);list.innerHTML=matches.length?matches.map((v,i)=>`<button type="button" class="via-suggestion" data-i="${i}">${esc(viaLabel(v))}</button>`).join(''):'<div class="via-empty">No hay coincidencias entre las vías registradas.</div>';list.hidden=false;input.setAttribute('aria-expanded','true');list.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>choose(matches[+b.dataset.i]));update()};input.onfocus=render;input.oninput=render;number.oninput=()=>{number.value=number.value.replace(/[^0-9]/g,'');update()};document.addEventListener('click',e=>{if(!root.contains(e.target))closeList()});update();return()=>{const v=vias.find(x=>x.id===hidden.value),num=number.value.trim();if(!v||!num){root.classList.add('invalid');return null}return{via_id:v.id,numero:num,direccion:`${viaLabel(v)} ${num}`}}}
async function modal(){if(!vias.length){try{await loadVias()}catch(e){alert(e.message);return}}const host=document.createElement('div');host.className='navidad-modal-backdrop';host.innerHTML=`<div class="navidad-modal"><div class="navidad-modal-head"><div><small>🎄 Navidad ${state.anio}</small><h2>Registrar niño o niña</h2></div><button class="navidad-close" aria-label="Cerrar">×</button></div><div class="navidad-note"><strong>Importante:</strong> si eres socio/a y el niño o niña ya está ingresado en SIGVE, no debes registrarlo nuevamente.</div><form id="navidad-form" class="navidad-grid"><label class="full">Nombre completo *<input name="nombre" required autocomplete="name"></label><label>RUT *<input name="rut" required placeholder="12.345.678-9"></label><label>Fecha de nacimiento *<input name="nacimiento" type="date" required></label><label>Edad<input name="edad" readonly placeholder="Se calcula automáticamente"></label><label>Niño/a *<select name="sexo" required><option value="">Selecciona</option><option value="M">Niño</option><option value="F">Niña</option></select></label><div class="full navidad-address-block"><label>Calle, pasaje o avenida *<div class="via-picker" data-navidad-via-picker><input name="via_busqueda" autocomplete="off" required placeholder="Busca una vía de Villa El Trigal" aria-expanded="false"><input name="via_id" type="hidden"><div class="via-suggestions" role="listbox" hidden></div></div></label><label>Número *<input name="numero_domicilio" inputmode="numeric" maxlength="10" required placeholder="Ej.: 1278"></label><p class="address-preview" data-address-preview>📍 Selecciona una vía registrada e ingresa el número.</p></div><label class="full">Teléfono de contacto *<div class="public-phone"><span>+56 9</span><input name="telefono" data-phone required inputmode="numeric" placeholder="12345678"></div></label><div class="full navidad-actions"><button class="button primary" type="submit">Registrar</button><button class="button secondary" type="button" data-close>Cancelar</button></div><p class="full navidad-status" aria-live="polite"></p></form></div>`;document.body.append(host);host.querySelector('.navidad-close').onclick=close;host.querySelector('[data-close]').onclick=close;host.onclick=e=>{if(e.target===host)close()};const f=host.querySelector('form'),getAddress=bindVia(f),r=f.rut,n=f.nacimiento;r.oninput=()=>r.value=formatRut(r.value);n.onchange=()=>f.edad.value=age(n.value)===''?'':`${age(n.value)} años`;window.SIGVE_PHONE?.enhance(f.telefono);f.onsubmit=e=>submit(e,getAddress);}
async function submit(e,getAddress){e.preventDefault();const f=e.currentTarget,st=f.querySelector('.navidad-status'),btn=f.querySelector('[type=submit]'),addr=getAddress();if(!addr){st.className='full navidad-status err';st.textContent='Selecciona una vía registrada e ingresa el número del domicilio.';return}const tel=window.SIGVE_PHONE?.getDbValue(f.telefono)||('+'+digits(f.telefono.value));if(!tel){st.className='full navidad-status err';st.textContent='Revisa el teléfono de contacto.';return}btn.disabled=true;st.textContent='Registrando…';try{const{data,error}=await sb.rpc('registrar_navidad_publica_v3',{p_nombre:f.nombre.value.trim(),p_rut:f.rut.value,p_fecha_nacimiento:f.nacimiento.value,p_sexo:f.sexo.value,p_via_id:addr.via_id,p_numero_domicilio:addr.numero,p_telefono:tel});if(error)throw error;if(data==='YA_SIGVE'){st.className='full navidad-status ok';st.textContent='Este niño o niña ya está registrado en SIGVE. No es necesario volver a inscribirlo.'}else if(data==='YA_EXTERNO'){st.className='full navidad-status ok';st.textContent=`Este niño o niña ya fue registrado para Navidad ${state.anio}.`}else{st.className='full navidad-status ok';st.textContent=`Registro realizado correctamente para Navidad ${state.anio}.`;f.reset();f.edad.value='';f.querySelector('[data-address-preview]').textContent='📍 Selecciona una vía registrada e ingresa el número.'}}catch(x){st.className='full navidad-status err';st.textContent=x.message||'No fue posible registrar.'}finally{btn.disabled=false}}
async function init(){if(!window.supabase||!window.PORTAL_CONFIG)return;sb=window.supabase.createClient(window.PORTAL_CONFIG.supabaseUrl,window.PORTAL_CONFIG.supabaseAnonKey);const block=$('#navidad-publica');if(!block)return;block.hidden=true;const{data,error}=await sb.rpc('estado_navidad_publica');if(error||!data?.length)return;state=data[0];if(!state.abierto)return;block.querySelector('[data-navidad-year]').textContent=state.anio;block.querySelector('[data-navidad-status]').textContent='Inscripciones abiertas.';const btn=block.querySelector('[data-open-navidad]');btn.hidden=false;btn.onclick=modal;block.hidden=false;const key=`sigve-navidad-popup-${state.anio}`;if(!localStorage.getItem(key)){setTimeout(()=>{modal();localStorage.setItem(key,'1')},650)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
