(() => {
const cfg=window.PORTAL_CONFIG||{}; if(!window.supabase||!cfg.supabaseUrl)return; const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=d=>d?new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'long',year:'numeric'}).format(new Date(d+'T12:00:00')):'';
async function get(table,order='creado_en'){const{data,error}=await sb.from(table).select('*').eq('publicado',true).order(order,{ascending:false});if(error){console.warn(table,error);return[]}return data||[]}
async function loadAnuncios(){const rows=(await get('anuncios')).filter(x=>!x.fecha_vencimiento||new Date(x.fecha_vencimiento)>new Date());const el=document.getElementById('announcements-grid');if(!el||!rows.length)return;rows.sort((a,b)=>Number(b.destacado)-Number(a.destacado));el.innerHTML=rows.map(x=>`<article class="announcement-card"><span class="announcement-type">${x.destacado?'📌 ':''}${esc(x.categoria)}</span><h3>${esc(x.titulo)}</h3><p>${esc(x.descripcion).replace(/\n/g,'<br>')}</p><div class="announcement-meta">${x.fecha_evento?`<span>📅 ${fmt(x.fecha_evento)}${x.hora_evento?' · '+esc(x.hora_evento.slice(0,5)):''}</span>`:''}${x.lugar?`<span>📍 ${esc(x.lugar)}</span>`:''}</div></article>`).join('')}
async function loadNoticias(){const rows=await get('noticias','fecha_publicacion');const el=document.getElementById('dynamic-news');if(!el||!rows.length)return;el.innerHTML=rows.map(x=>`<article class="dynamic-card">${x.imagen_url?`<img src="${esc(x.imagen_url)}" alt="${esc(x.titulo)}">`:''}<div><span class="badge">${esc(x.categoria||'Comunidad')}</span><h3>${esc(x.titulo)}</h3><p>${esc(x.resumen||x.contenido)}</p></div></article>`).join('')}
async function loadActividades(){const rows=await get('actividades','fecha');const el=document.getElementById('dynamic-activities');if(!el||!rows.length)return;el.innerHTML=rows.map(x=>`<article class="dynamic-card">${x.imagen_url?`<img src="${esc(x.imagen_url)}" alt="${esc(x.titulo)}">`:''}<div><span class="badge">📅 ${fmt(x.fecha)}</span><h3>${esc(x.titulo)}</h3><p>${esc(x.descripcion)}</p>${x.lugar?`<p><strong>Lugar:</strong> ${esc(x.lugar)}</p>`:''}</div></article>`).join('')}
async function loadGaleria(){const rows=await get('galeria');const el=document.getElementById('dynamic-gallery');if(!el||!rows.length)return;el.innerHTML=rows.map(x=>`<button class="gallery-item" onclick="openLightbox('${esc(x.imagen_url)}')"><img src="${esc(x.imagen_url)}" alt="${esc(x.titulo||'Fotografía de la comunidad')}"></button>`).join('')}
Promise.all([loadAnuncios(),loadNoticias(),loadActividades(),loadGaleria()]);
})();
