(() => {
  const cfg=window.PORTAL_CONFIG||{};
  const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
  let token=sessionStorage.getItem('sigve_portal_token'), children=[], currentMemberNumber='';
  const $=(id)=>document.getElementById(id);
  const msg=(id,text,type='')=>{const e=$(id);e.textContent=text;e.className=`message ${type}`};
  const rpc=async(fn,args={})=>{const {data,error}=await sb.rpc(fn,args);if(error)throw new Error(error.message);return data};
  const fmtDate=(v)=>v?new Intl.DateTimeFormat('es-CL',{timeZone:'UTC'}).format(new Date(v+'T00:00:00Z')):'—';
  const escape=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const normalizeMemberNumber=(value)=>{const digits=String(value??'').replace(/\D/g,'');if(!digits)return null;const number=Number.parseInt(digits,10);return Number.isSafeInteger(number)?number:null};

  $('rutForm').addEventListener('submit',async(e)=>{e.preventDefault();msg('authMsg','Validando datos…');try{const memberNumber=normalizeMemberNumber($('memberNumber').value);if(memberNumber===null)throw new Error('Los datos ingresados son incorrectos');const t=await rpc('portal_socio_ingresar',{p_rut:$('rut').value,p_numero_socio:memberNumber});if(!t)throw new Error('Los datos ingresados son incorrectos');token=t;sessionStorage.setItem('sigve_portal_token',token);await enter()}catch(err){msg('authMsg',err.message.includes('tempor')?err.message:'Los datos ingresados son incorrectos','error')}});
  document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab-panel').forEach(p=>p.hidden=p.id!==b.dataset.tab)});

  async function enter(){try{const rows=await rpc('portal_socio_mis_datos',{p_token:token});const s=rows?.[0];if(!s)throw new Error();currentMemberNumber=normalizeMemberNumber(s.numero_socio);$('loginView').hidden=true;$('portalView').hidden=false;$('logout').hidden=false;$('welcomeName').textContent=s.nombre_completo;$('numero').textContent=s.numero_socio||'—';$('rutRead').textContent=s.rut;$('fechaIngreso').textContent=fmtDate(s.fecha_ingreso);$('estado').textContent=s.estado;$('direccion').value=s.direccion||'';$('telefono').value=s.telefono||'';$('correo').value=s.correo||'';await loadChildren()}catch(e){sessionStorage.removeItem('sigve_portal_token');token=null;$('loginView').hidden=false;$('portalView').hidden=true;$('logout').hidden=true;msg('authMsg','Tu sesión venció. Ingresa nuevamente.','error')}}
  $('dataForm').addEventListener('submit',async(e)=>{e.preventDefault();msg('dataMsg','Guardando…');try{await rpc('portal_socio_actualizar_datos',{p_token:token,p_direccion:$('direccion').value,p_telefono:$('telefono').value,p_correo:$('correo').value});msg('dataMsg','Datos actualizados correctamente.','success')}catch(err){msg('dataMsg',err.message,'error')}});
  async function loadChildren(){children=await rpc('portal_socio_listar_ninos',{p_token:token})||[];const box=$('childrenList');if(!children.length){box.innerHTML='<div class="notice">No hay niños o niñas registrados actualmente.</div>';return}box.innerHTML=children.map(n=>`<article class="child-card"><div><h3>${escape(n.nombre_completo)}</h3><p>RUT: ${escape(n.rut)} · Nacimiento: ${fmtDate(n.fecha_nacimiento)}</p><p>${escape(n.parentesco||'Hijo(a)')}${n.tiene_condicion_especial?' · Con consideración especial':''}</p></div><div class="child-actions"><button data-edit="${n.id}">Editar</button><button data-delete="${n.id}">Retirar</button></div></article>`).join('');box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openChild(children.find(n=>n.id===b.dataset.edit)));box.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeChild(b.dataset.delete))}
  $('newChild').onclick=()=>openChild(); $('childSpecial').onchange=()=>{$('specialFields').hidden=!$('childSpecial').checked};
  function openChild(n=null){$('childForm').reset();$('childParticipates').checked=true;$('childRelation').value='Hijo(a)';$('childId').value=n?.id||'';$('childTitle').textContent=n?'Editar registro':'Agregar niño o niña';if(n){$('childName').value=n.nombre_completo||'';$('childRut').value=n.rut||'';$('childBirth').value=n.fecha_nacimiento||'';$('childSex').value=n.sexo||'';$('childRelation').value=n.parentesco||'Hijo(a)';$('childParticipates').checked=n.participa_actividades!==false;$('childSpecial').checked=!!n.tiene_condicion_especial;$('childConditions').value=(n.condiciones_especiales||[]).join(', ');$('childOther').value=n.condicion_otro||'';$('childNotes').value=n.observaciones_especiales||'';$('childConsent').checked=!!n.autoriza_datos_sensibles}$('specialFields').hidden=!$('childSpecial').checked;msg('childMsg','');$('childDialog').showModal()}
  $('saveChild').addEventListener('click',async(e)=>{e.preventDefault();if(!$('childForm').reportValidity())return;msg('childMsg','Guardando…');try{await rpc('portal_socio_guardar_nino',{p_token:token,p_id:$('childId').value||null,p_nombre:$('childName').value,p_rut:$('childRut').value,p_fecha:$('childBirth').value,p_sexo:$('childSex').value,p_parentesco:$('childRelation').value,p_participa:$('childParticipates').checked,p_tiene_condicion:$('childSpecial').checked,p_condiciones:$('childSpecial').checked?$('childConditions').value.split(',').map(x=>x.trim()).filter(Boolean):[],p_otro:$('childOther').value,p_observaciones:$('childNotes').value,p_autoriza:$('childConsent').checked});$('childDialog').close();await loadChildren();msg('familyMsg','Registro guardado.','success')}catch(err){msg('childMsg',err.message,'error')}});
  async function removeChild(id){if(!confirm('¿Retirar este registro del grupo familiar? Se conservará como antecedente histórico.'))return;try{await rpc('portal_socio_eliminar_nino',{p_token:token,p_id:id});await loadChildren();msg('familyMsg','Registro retirado.','success')}catch(err){msg('familyMsg',err.message,'error')}}
  $('noChildren').onclick=async()=>{if(!confirm('¿Confirmas que actualmente no tienes niños o niñas que registrar?'))return;try{await rpc('portal_socio_declarar_sin_ninos',{p_token:token});msg('familyMsg','Declaración registrada correctamente.','success')}catch(err){msg('familyMsg',err.message,'error')}};
  $('resignForm').addEventListener('submit',async(e)=>{e.preventDefault();if(normalizeMemberNumber($('resignConfirm').value)!==currentMemberNumber){msg('resignMsg','El número de socio no coincide.','error');return}if(!confirm('Esta es la confirmación final. ¿Registrar tu renuncia voluntaria?'))return;msg('resignMsg','Registrando renuncia…');try{await rpc('portal_socio_renunciar_numero',{p_token:token,p_numero_socio:normalizeMemberNumber($('resignConfirm').value),p_motivo:$('resignReason').value});sessionStorage.removeItem('sigve_portal_token');alert('Tu renuncia voluntaria quedó registrada.');location.href='index.html'}catch(err){msg('resignMsg',err.message,'error')}});
  $('logout').onclick=async()=>{try{if(token)await rpc('portal_socio_cerrar_sesion',{p_token:token})}catch{}sessionStorage.removeItem('sigve_portal_token');location.reload()};
  if(token)enter();
})();
