(() => {
const cfg=window.PORTAL_CONFIG||{};if(!window.supabase||!cfg.supabaseUrl)return;
const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
const monthNames=['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
const dayNames=['Lu','Ma','Mi','Ju','Vi','Sá','Do'];
const rutClean=r=>String(r||'').replace(/[^0-9kK]/g,'').toUpperCase();
const formatRut=r=>{const c=rutClean(r);if(c.length<2)return c;let b=c.slice(0,-1),dv=c.slice(-1),out='';while(b.length>3){out='.'+b.slice(-3)+out;b=b.slice(0,-3)}return b+out+'-'+dv};
function validRut(r){r=rutClean(r);if(r.length<2)return false;let body=r.slice(0,-1),dv=r.slice(-1),sum=0,m=2;for(let i=body.length-1;i>=0;i--){sum+=+body[i]*m;m=m===7?2:m+1}const x=11-(sum%11),e=x===11?'0':x===10?'K':String(x);return dv===e}
const phoneDigits=v=>{let d=String(v||'').replace(/\D/g,'');if(d.startsWith('56'))d=d.slice(2);if(d.startsWith('9'))d=d.slice(1);return d.slice(0,8)};
const formatPhone=v=>{const d=phoneDigits(v);return d?`+56 9 ${d.slice(0,4)}${d.length>4?' '+d.slice(4):''}`:''};
const phoneDb=v=>{const d=phoneDigits(v);return d.length===8?`+569${d}`:null};
function iso(y,m,d){return `${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
function readable(y,m,d){return `${d} de ${monthNames[m].toLowerCase()} de ${y}`}
function selectDate(dateIso,label){const a=document.getElementById('rental-whatsapp');if(a){const text=`Hola, me gustaría solicitar el arriendo de la Sede Social Villa El Trigal para el día ${label}. Entiendo que la reserva queda confirmada únicamente cuando la Junta de Vecinos responda por WhatsApp.`;a.href=`https://wa.me/56974596793?text=${encodeURIComponent(text)}`}const p=document.getElementById('selected-date-text');if(p)p.innerHTML=`Fecha seleccionada: <strong>${label}</strong>. Presiona el botón para enviar la solicitud.`;document.querySelectorAll('.calendar-day.selected').forEach(e=>e.classList.remove('selected'));document.querySelector(`[data-date="${dateIso}"]`)?.classList.add('selected')}
async function renderCalendar(){const host=document.getElementById('rental-calendars'),status=document.getElementById('calendar-sync-status');if(!host)return;host.innerHTML='<p>Cargando calendario…</p>';const start=new Date();start.setDate(1);const end=new Date(start.getFullYear()+1,start.getMonth(),1);const{data,error}=await sb.from('reservas_publicas').select('*').gte('fecha_evento',iso(start.getFullYear(),start.getMonth(),1)).lt('fecha_evento',iso(end.getFullYear(),end.getMonth(),1));if(error){host.innerHTML='<p>No fue posible cargar el calendario.</p>';if(status)status.textContent='Error al consultar disponibilidad.';return}const map=new Map((data||[]).map(x=>[x.fecha_evento,x]));host.innerHTML='';for(let k=0;k<12;k++){const y=start.getFullYear()+Math.floor((start.getMonth()+k)/12),m=(start.getMonth()+k)%12,card=document.createElement('article');card.className='month-card';card.innerHTML=`<h4>${monthNames[m]} ${y}</h4>`;const days=document.createElement('div');days.className='month-days';dayNames.forEach(n=>days.insertAdjacentHTML('beforeend',`<span class="day-name">${n}</span>`));const off=(new Date(y,m,1).getDay()+6)%7;for(let i=0;i<off;i++)days.insertAdjacentHTML('beforeend','<span class="calendar-blank"></span>');const count=new Date(y,m+1,0).getDate();for(let d=1;d<=count;d++){const key=iso(y,m,d),entry=map.get(key),btn=document.createElement('button');btn.type='button';btn.dataset.date=key;btn.textContent=d;const past=new Date(y,m,d)<new Date(new Date().setHours(0,0,0,0));if(past){btn.className='calendar-day past';btn.disabled=true;btn.title='Fecha pasada'}else if(entry){const cls=entry.tipo==='zumba'?'zumba':entry.tipo==='actividad'?'activity':'reserved';btn.className=`calendar-day ${cls}`;btn.disabled=true;btn.title=entry.tipo==='arriendo'?'Reservado':entry.descripcion_publica||entry.tipo}else{btn.className='calendar-day available';btn.onclick=()=>selectDate(key,readable(y,m,d));btn.title='Disponible para consultar'}days.appendChild(btn)}card.appendChild(days);host.appendChild(card)}if(status)status.textContent='Calendario actualizado desde el sistema de reservas.'}
function setupForm(){const f=document.getElementById('public-socio-form'),m=document.getElementById('public-socio-message');if(!f)return;const rut=f.elements.rut,phone=f.elements.telefono;rut.dataset.rut='1';rut.addEventListener('input',()=>rut.value=formatRut(rut.value));phone.addEventListener('input',()=>phone.value=formatPhone(phone.value));f.onsubmit=async e=>{e.preventDefault();const fr=e.currentTarget,r=formatRut(fr.rut.value),t=phoneDb(fr.telefono.value);if(!validRut(r)){m.textContent='Revisa el RUT ingresado.';return}if(!t){m.textContent='El celular debe tener 8 dígitos después de +56 9.';return}m.textContent='Enviando…';const{error}=await sb.from('solicitudes_socios').insert({nombre_completo:fr.nombre.value.trim(),rut:r,direccion:fr.direccion.value.trim(),telefono:t,correo:fr.correo.value.trim()||null,observaciones:fr.observaciones.value.trim()||null,estado:'pendiente'});if(error){m.textContent='No se pudo enviar: '+error.message;return}fr.reset();m.textContent='Solicitud enviada correctamente. La directiva la revisará.'}}
document.addEventListener('DOMContentLoaded',()=>{renderCalendar();setupForm()});
})();
